remote_theme: pmarsceill/just-the-docs

title: ""
logo: "/assets/IDEAtlas_transp.png"
logo_width: 150
description: "Technical workshop on mapping Deprived Urban Areas using Earth Observation and AI"

# Exclude from search and build
exclude:
  - assets/tmp
  - docs/tmp
  - node_modules

# Just-the-docs theme settings
color_scheme: light
search_enabled: false
heading_anchors: true

# Defaults for pages
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"